### ISSUE TITLE
php not found!

### ISSUE THREAD

**Issue by xstrex** [JustinAiken/openhab_monitor#3]
Hey, thanks for writing this up, I think it could be very useful. But I've run into a bit of a snag. php is not on  the wink, at least in my version. 
[root@flex-dvt ]# find |grep php
./bin/openhab_monitor.php
[root@flex-dvt ]#

[root@flex-dvt ]# /usr/bin/php
-sh: /usr/bin/php: not found

Version info: 
[root@flex-dvt database]# for i in `ls cf_*`; do cat $i; done
00.01
00.01
00.12
00.01
02.49

Any suggestions?

**Comment by JustinAiken** [comment]
Yeah, I think they took it out in later firmwares...

It used to be there:

``` bash
$ cat $(ls /database/cf*)
00.01
00.01
00.08
00.01
00.86

$ which php
/usr/bin/php

$ php -v
PHP 5.5.10 (cli) (built: Mar 26 2014 18:45:38)
```

(I'm still on .86, no hurry to upgrade, haha)

You could try just `scp`ing the `php` binary to your hub, it might still work..
